### ISSUE TITLE
[SiliconFlow][Bug][Hygon] FlagGems import fails after #5557

### ISSUE THREAD

**Issue by winfan1314** [FlagOpen/FlagGems#5572]
## Description

After #5557 was merged, importing `flag_gems` on the Hygon backend fails during backend operator initialization. This prevents pytest from collecting any Hygon tests, including tests unrelated to `weight_norm`.

## Reproduction

```bash
export GEMS_VENDOR=hygon
python -c "import flag_gems"
```

The import terminates with:

```text
RuntimeError: Failed to import vendor extra lib: cannot import name 'backward' from '_hygon.ops.weight_norm'
```

## Root cause

Commit `4efe5933feeb533f43aa9ea4f2d6e970feb8348e` from #5557 changed `src/flag_gems/runtime/backend/_hygon/ops/__init__.py` to import `forward` and `backward` from `weight_norm.py`, but that module does not define either symbol. The failure therefore occurs while importing the backend package, before the requested operator tests start.

## Impact

All Hygon CI jobs based on the affected master revision fail at `tests/conftest.py` while importing FlagGems. The same failure is currently visible in multiple otherwise unrelated PRs:

- #5064: https://github.com/flagos-ai/FlagGems/actions/runs/32095066420/job/95584855354
- #5067: https://github.com/flagos-ai/FlagGems/actions/runs/32095476523/job/95586002771
- #5339: https://github.com/flagos-ai/FlagGems/actions/runs/32095086037/job/95584917862

## Expected behavior

`import flag_gems` should succeed on Hygon. The backend export list should only import symbols actually defined by `weight_norm.py`, or the missing wrappers should be implemented and exported consistently.

**Comment by winfan1314** [comment]
Seems resolved after #5573
