### PR TITLE
[FlagGems Operator Development Competition] Add scatter_reduce operator (full trio: scatter_reduce.two / scatter_reduce_.two / scatter_reduce.two_out)

### PR DESCRIPTION
**Pull request by IveGotMagicBean**
# PR Body

## PR Category

**Operator**

## Type of Change

**New Feature**

## Description

This PR registers the full `scatter_reduce` ATen schema trio under FlagGems for the Operator Development Competition (mid-difficulty operator):

* `scatter_reduce.two`        — out-of-place
* `scatter_reduce_.two`        — in-place (replaces the partial placeholder in `src/flag_gems/ops/scatter_reduce_.py`)
* `scatter_reduce.two_out`     — out-variant

All three share a single unified implementation in `src/flag_gems/ops/scatter_reduce.py` (~950 lines, 4 Triton kernels). Supported reductions: `sum`, `prod`, `mean`, `amax`, `amin`, with both `include_self=True` and `False`. Supported dtypes (all paths Triton-native, no CPU fallback): `float16`, `float32`, `bfloat16` (sm_80+), `int16`, `int32`, `int64`.

### 1. Mean is 2 kernel launches, not 3

Prior submissions compose `scatter_add_` × 2 + division kernel = three launches. We fuse the running sum and the running count into one Triton kernel (`_scatter_mean_fused_kernel`), then run a single `_mean_safe_div_float_kernel` that loads, casts, clamps, and divides in one pass. This saves roughly 30 us of cumulative launch overhead on small shapes -- which is the difference between a 0.1x and a 1.0x speedup at the 256x256 regime.

### 2. int16 stays on the GPU

Prior submissions fall back to a full CPU roundtrip for `int16` (Triton lacks a 16-bit integer `atomic_add`). We promote `int16 -> int32` device-side, run the kernel, and write back. No CPU traffic.

### 3. Two-pass amax/amin for fp32/fp64

For dtypes where `tl.atomic_max`/`tl.atomic_min` are available (fp32, fp64, int), we use a two-pass approach: native atomic_max/min for non-NaN sources plus an `atomic_xchg`-on-NaN pass. This replaces the CAS-loop entirely on the contented large-shape cases, where each CAS retry stalls the warp. On benchmark workloads with no NaN, pass 2 scans once and performs zero atomics.

### 4. Our own sum kernel

We do not piggyback on the existing `scatter_add_` helper for sum because its `scatter_add_1` codegen path has an in-place contract bug for fp32 + dim != last (the function returns the result tensor but never writes back into `origin`, breaking in-place semantics). We provide a dedicated `_scatter_sum_kernel` with proper accumulator-dtype promotion (fp16 stays native on Volta+, bf16 promotes on pre-Ampere, int16 promotes to int32).

### 5. Robust edge cases instead of CPU detours

Scalar `self` (ndim==0), ranks up to 8, alias (`out is inp`), empty tensors, and non-contiguous strides all stay on-device. Internal overlap is detected via the public `shape_utils.has_internal_overlapping` helper rather than the private `torch._C._overlaps` API.

## Accuracy

The full pytest suite at `tests/test_scatter_reduce.py` runs 665 parametrised cases covering:

* All 5 reductions × 3 wrappers × `include_self in {True, False}`
* dtypes: fp16, fp32, bf16 (sm_80+), int16, int32, int64
* ranks 1 .. 5
* negative `dim`
* alias case (`out=inp`)
* empty index / empty source
* scalar (0-rank) self
* +inf, -inf, NaN propagation
* representative large shape (1024 × 1024)
* error paths: invalid `dim`, invalid `reduce`, non-int64 `index`, rank/shape mismatch

**Result: 665 passed, 0 failed, 50 skipped (bf16 on sm_75)** -- using the competition rubric tolerances (`fp16: atol=1e-3`, `fp32: atol=1.3e-6`, `bf16: 1.6e-2`).

```bash
export GEMS_VENDOR=nvidia
export PYTHONPATH=src
pytest tests/test_scatter_reduce.py -v
```

## Performance

Benchmark uses `benchmark/test_scatter_reduce.py` over 5 workload-driven shapes from `core_shapes.yaml`: `(256, 256)`, `(1024, 1024)`, `(1024, 8192)`, `(4096, 4096)`, `(1024, 65536)`. Workloads cover transformer hidden-state pool, recsys embedding aggregation, and graph pooling. 85 (op_name × reduce × include_self × dtype × shape) cases tested.

Result on NVIDIA RTX 2080 Ti (Turing, sm_75, CUDA 12.4, Triton 3.2.0):

| Metric                        | Value       |
| ----------------------------- | ----------- |
| Median speedup vs PyTorch    | **1.133×**  |
| Mean speedup                  | 1.135×      |
| Max                           | 2.008×      |
| Speedup ≥ 0.9× (rubric floor) | **62 / 85** (73%) |
| Speedup ≥ 1.0×                | 59 / 85     |
| Speedup ≥ 1.2×                | 33 / 85     |
| Speedup ≥ 1.5×                | 13 / 85     |

By reduction:

| Reduce | n   | min    | median | max    | mean   |
| ------ | --- | ------ | ------ | ------ | ------ |
| amin   | 25  | 0.724× | **1.339×** | 2.008× | 1.324× |
| **mean** | 15  | 0.898× | **1.391×** | 1.711× | 1.331× |
| amax   | 15  | 0.498× | 1.124× | 1.746× | 1.088× |
| sum    | 15  | 0.593× | 1.090× | 1.232× | 1.038× |
| prod   | 15  | 0.465× | 0.683× | 1.320× | 0.770× |

Adaptive BLOCK sizing (128 for small N, 2048 for >= 16M elements on the
atomic-add kernels, smaller for the CAS-loop kernels where the per-iteration
`tl.sum` reduction bloats with warp count) keeps the launch grid balanced
across the range of workload shapes.

```bash
pytest benchmark/test_scatter_reduce.py -v -s --tb=short --level comprehensive --mode kernel
```

## Implementation notes

* `_scatter_sum_kernel`, `_scatter_mean_fused_kernel`, `_scatter_cas_reduce_kernel`, `_scatter_float_minmax_kernel`, `_scatter_nan_xchg_kernel`, `_scatter_native_int_minmax_kernel`, `_mean_safe_div_float_kernel`, `_mean_safe_div_int_kernel` -- 8 Triton kernels in total. They share a runtime meta-tensor layout `[shape, inp_stride, index_stride, src_stride]` × `rank`, packed once per call and cached in `_META_CACHE` for repeated training-loop calls.
* Rank is erased at runtime via `RANK: tl.constexpr`, so Triton specialises one compiled kernel per rank instead of paying for an upper-bound MAX_RANK loop.
* Validation, scalar handling, and dim normalisation all happen Python-side before the meta-tensor build, so the kernel never has to special-case ndim==0 or negative dims.

## Progress

- [x] All 5 reductions × `include_self` in {True, False} implemented
- [x] All 3 wrappers (out-of-place, in-place, out-variant) registered
- [x] 665 / 665 pytest cases pass on 2080 Ti
- [x] 14 / 14 benchmark framework cases pass
- [x] Median speedup 1.077× over PyTorch native on a 2080 Ti
- [x] `conf/operators.yaml` entries for `scatter_reduce.two` and `scatter_reduce.two_out` added
- [x] `core_shapes.yaml` entries with workload-relevant shapes
- [ ] Pre-commit / flake8 / black / isort cleanup pass (pending)

## Hardware tested

* NVIDIA RTX 2080 Ti (Turing sm_75) -- self-provided compute track.
* bf16 path validated correct via the smoke driver but skipped from the bench/pytest sweeps on sm_75 because Triton 3.x emits `.bf16` PTX instructions that require sm_80+. On Ampere or newer the bf16 path runs identically to fp16 (native atomic_add).

### CODE REVIEW

**Comment by IveGotMagicBean** [comment]
Just rebased onto current master (ab4bde3) — that should resolve the `test_triton_lighting_indexer_k_tiled_interface.py` F401, since #3263 already removed the file. The new workflow runs are pending maintainer approval; could you trigger them when you have a moment?

For context, the two CI failures from the previous run both trace back to master rather than this PR:

**1. code-style**

The F401s my changes introduced (`tests/test_scatter_reduce.py`, `benchmark/test_scatter_reduce.py`) were fixed in the earlier force-push. The remaining one —

```
benchmark/test_trunc_divide.py:4:1: F401 '.consts' imported but unused
```

— was introduced in #3211 and is still on master. Happy to fold a one-line cleanup into this PR if you'd rather not handle it separately.

**2. python-op**

This one previously failed at conftest import, before any scatter_reduce test runs:

```
src/flag_gems/fused/geglu.py:12: in <module>
    pow = tl_extra_shim.pow
E   AttributeError: module 'triton.language.math' has no attribute 'pow'
```

`fused/geglu.py` isn't touched by this PR — looks like a Triton version mismatch on the runner. Could you share which Triton version the python-op job runs against? Locally on Triton 3.2.0 / RTX 2080 Ti the full scatter_reduce suite is green: 665 passed, 0 failed, 50 skipped.

Thanks!

**Comment by douxetpur** [comment]
Hi, thank you for your participation in the FlagOS Open Computing Competition 🙏

After review, we have chosen to move forward with a different implementation for this operator. As a result, this PR will be closed.

We appreciate your time and contribution, and hope to see more of your submissions in the future.
