### ISSUE TITLE
[Bug] moe_align_block_size TLE kernel fails to legalize on Hygon/HCU; HAS_TLE gate not vendor-aware (severe startup slowdown)

### ISSUE THREAD

**Issue by ckxud** [FlagOpen/FlagGems#4427]
> Note: this has already been fixed on master by #3975 + #3990 (shipped in v5.3.0). This issue mainly records the problem, traces the fix, and asks about handling for users still on older versions.

## Environment

| Component | Version |
|-----------|---------|
| flag_gems | 5.0.2, commit `2718037d887cd6a3143474da0224648e40c5004f` (before the fix) |
| triton | flagtree 0.6.0+hcu3.6 (`triton.__version__=3.6.0`, hcu backend) |
| vLLM | 0.20.0+empty |
| vllm-plugin-fl | 0.2.0, commit `48af29e21491700a38020ab031af5d3b90e6795e` |
| PyTorch | 2.10.0+das.opt1.dtk2604 |
| Hardware | Hygon DCU (`vendor_name=hygon`) |

## Symptom

With graph compilation enabled, after getting past the vllm-plugin-FL FixFunctionalizationPass crash (via compile-cache hit or after that fix), startup becomes extremely slow during the CUDA graph capture phase: each capture step ~33-44s, 51 steps ~28-36 min (normal would be tens of seconds to a couple minutes). Each step repeatedly prints an MLIR compilation failure; the error repeats thousands of times over a single startup.

## Error (printed repeatedly)

```
src/flag_gems/fused/moe_align_block_size.py:308:56:
  error: failed to legalize operation 'tle.local_pointers' that was explicitly marked illegal
src/flag_gems/fused/moe_align_block_size.py:164:28:
  error: failed to legalize operation 'tle.distributed_barrier' that was explicitly marked illegal
src/flag_gems/fused/moe_align_block_size.py:132:0 / :258:0:
  error: Failures have been detected while processing an MLIR pass pipeline
  note: Pipeline failed while executing 'ConvertTritonHCUGPUToLLVM' on 'builtin.module'
```

Lines 132 / 164 / 258 / 308, corresponding to the `moe_align_block_size_tle_cluster_fused` and `moe_align_block_size_tle_atomic_fused_coop` TLE variants.

## Root cause

1. The `moe_align_block_size` kernel takes the TLE (Triton Language Extension) path, using `tle.distributed_barrier` / `tle.local_pointers`. The flagtree 0.6.0+hcu3.6 HCU backend cannot legalize these two ops in `ConvertTritonHCUGPUToLLVM` (see the FlagTree side issue: flagos-ai/FlagTree#727).
2. Whether TLE is taken is decided by `has_triton_tle(3,6,0)` -> `HAS_TLE` at the top of the kernel. The old logic (`2718037d`) only checked triton version >= 3.6.0 + whether `tle` can be imported, **without distinguishing vendor**. On HCU, flagtree reports triton 3.6.0 and `tle` is importable -> `HAS_TLE=True` -> takes TLE -> fails to compile on HCU.
3. The op uses the `default.flagos` path, and the Reference backend lacks it (`'ReferenceBackend' object has no attribute 'moe_align_block_size'`), so there is no fallback after compile failure; it re-compiles on every shape / every capture.

## Existing fix (confirmation + trace)

Fixed on master by two PRs (both merged 2026-06-11, shipped in v5.3.0):

- **#3975** `Fix tle vendor`: `utils/triton_version_utils.py` adds `is_support_vendor()` (uses `DeviceDetector` to get vendor -> reads `vendor_info.tle_enabled`); `has_triton_tle` changes its trailing `return True` to `return is_support_vendor()`.
- **#3990** `[TLE] Fix tle_enabled`: `backend_utils.py` `VendorInfo` adds `tle_enabled: bool = False` (default False) and sets `tle_enabled=True` explicitly for `_nvidia` / `_mthreads` / `_enflame`.

Fix mechanism: `_hygon/__init__.py` does not set `tle_enabled` -> defaults to False -> `has_triton_tle` returns False on HCU -> `HAS_TLE=False` -> the TLE kernel is not taken, avoiding the HCU legalization failure.

> Tracing note: line 526 of `moe_align_block_size.py` (the `if HAS_TLE and ...` gate) itself was not changed; the real fix lives in `triton_version_utils.py` + each vendor `__init__.py`. A git blame of only the kernel file misses this fix. The TLE path was introduced by #1597 `support moe_align_block_size tle`.

## Asks

1. Confirm the fix is effective for Hygon/HCU (`_hygon` defaulting to `tle_enabled=False`).
2. If there are users on older versions (e.g. 5.0.x), please state the minimum fixed version (v5.3.0) or provide a backport / workaround.
3. Coordination with vllm-plugin-FL: the current plugin (`48af29e`) is only compatible with the old FlagGems `backend.device` import path; upgrading to v5.3.0 (which contains this fix) triggers a plugin import failure (see the vllm-plugin-FL side issue), so the plugin needs a matching update.

## Related

- FlagTree side root cause: flagos-ai/FlagTree#727
- vllm-plugin-FL FixFunctionalizationPass / flagos-ai/vllm-plugin-FL#242: the "first hurdle" when graph is enabled.
- vllm-plugin-FL import incompatibility with newer FlagGems: flagos-ai/vllm-plugin-FL#253.
